import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Toaster } from "components/ui/sonner";
import "./globals.css";
import { ExitModal } from "components/modals/exit-modal";
import { HeartsModal } from "components/modals/hearts-modal";
import { PracticeModal } from "components/modals/practice-modal";

const font = Nunito({
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={font.className}
        >
          <Toaster />
          <ExitModal />
          <HeartsModal


          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
